categories:
- Statistics
description: Interval-Wise Testing for Omics Data
long_description: |
  Implementation of the Interval-Wise Testing (IWT) for omics data. This
  inferential procedure tests for differences in "Omics" data between two groups
  of genomic regions (or between a group of genomic regions and a reference
  center of symmetry), and does not require fixing location and scale at the
  outset.
name: iwtomics
owner: fabio
homepage_url: https://bioconductor.org/packages/release/bioc/html/IWTomics.html
remote_repository_url: https://github.com/fabio-cumbo/IWTomics4Galaxy
type: unrestricted
